import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { getClient } from '@kodadot1/uniquery'


const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const client = getClient()
  const id = '2305670031'
  const query = client.collectionById(id)
  const result = await client.fetch(query)

  console.log(result)

  return {
    props: {}
  }
}


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p>
            Hello world!
          </p>
        </div>

      </main>
    </>
  )
}
