import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { InferGetStaticPropsType } from 'next'
import ProductCard from '@/components/ProductCard'

import { extendFields, getClient } from '@kodadot1/uniquery'



export default function Product() {

  return (
    <>
      <Head>
        <title>ProductPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Product Page

      </main>
    </>
  )
}
